variables:
  r_version: rocker/r-ver:4.3.2

stages:
  - r-container-build

r-container-build:
  stage: r-container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      mkdir -p /kaniko/.docker;
      printf "{
          \"auths\": 
              {
                  \"${CI_REGISTRY}\": { 
                      \"auth\": \"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"
                  }
              }
      }" \
      > /kaniko/.docker/config.json
    - >-
      cd ${CI_PROJECT_DIR};
      export ubuntu_packages=$(cat dependencies/Ubuntu);
      export r_packages=$(cat dependencies/R)
    - >-
      /kaniko/executor
      --context "./"
      --dockerfile "./Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/test:latest"