variables:
  R_IMAGE: index.docker.io/simonlenau/containr:4.3.3
  PYTHON_IMAGE: python:3.12

stages:
  - container-build

include:
  - local: '.gitlab-ci/templates/build-container.yaml'

r-container-build:
  extends: .build-container
  # Set base image
  variables:
    FROM_IMAGE: "${R_IMAGE}"
  before_script:
    # Export package lists
    - >- 
      export ubuntu_packages=$(cat dependencies/Ubuntu 2>/dev/null || return 0);
      export r_packages=$(cat dependencies/R 2>/dev/null || return 0);


python-container-build:
  extends: .build-container
  # Set base image
  variables:
    FROM_IMAGE: "${PYTHON_IMAGE}"
  before_script:
    # Export package lists
    - >- 
      export ubuntu_packages=$(cat dependencies/Ubuntu 2>/dev/null || return 0);
      export python_packages=$(cat dependencies/python 2>/dev/null || return 0);
