variables:
  R_IMAGE: index.docker.io/simonlenau/containr:4.3.3
  PYTHON_IMAGE: python:3.12

stages:
  - container-build
  - container-forward

include:
  - local: '.gitlab-ci/templates/build-container.yaml'
  - local: '.gitlab-ci/templates/forward-container.yaml'

R-container-build:
  extends: .build-container
  # Set base image
  variables:
    FROM_IMAGE: "${R_IMAGE}"
    install_dependencies: "ubuntu R"


python-container-build:
  extends: .build-container
  # Set base image
  variables:
    FROM_IMAGE: "${PYTHON_IMAGE}"
    install_dependencies: "ubuntu python"

R-container-forward:
  extends: .forward-container
  # Set base image
  variables:
    FROM_IMAGE: "${R_IMAGE}"

python-container-forward:
  extends: .forward-container
  # Set base image
  variables:
    FROM_IMAGE: "${PYTHON_IMAGE}"