#!/bin/bash
echo "Attempting to install packages:"
printf "\t - %s\n" ${@}

(apt-get update -y && apt-get install -y ${@}) >packages.log 2>&1 &&
    (echo "... successful!" && rm -rf packages.log) ||
    (sed -i 's/^/\t/' packages.log && cat packages.log && exit 1)
