#!/bin/sh
install_dependencies="R python"
function add_dependencies {
    if echo "${install_dependencies}" | grep -qie"\b${1}\b"; then
        entry="$(echo "${1}" | perl -p0e "s/(.)/\L\${1}/gmi")"
        echo "--build-arg \"${entry}_packages\"=\"\${${entry}_packages}\""
    fi
}


/kaniko/executor
    --context "./"
    --dockerfile "./Dockerfile"
    $(add_dependencies "ubuntu") \
    $(add_dependencies "R") \
    $(add_dependencies "python") \
    --build-arg "workdir"="/${CI_PROJECT_TITLE}/"
    --build-arg "outdir"="/${CI_PROJECT_TITLE}_output/"
    --build-arg "FROM_IMAGE"="${FROM_IMAGE}"
    --destination "${GITLAB_REGISTRY_PATH}:${image_vers}"
    --destination "${GITLAB_REGISTRY_PATH}:latest"
    --destination "${DOCKERHUB_REGISTRY_PATH}_${image_vers}"
    --destination "${DOCKERHUB_REGISTRY_PATH}_latest"







