#!/usr/bin/sh

function write_auth {
cat <<EOF
"${1}":
                {
                    "auth": 
                        "$(printf "${2}:${3}"  | base64 -w 0)"
                }
EOF
}


printf "%s" \
    "{
        \"auths\":
        {
            $(
                write_auth \
                    "${CI_REGISTRY}/" \
                    "${CI_REGISTRY_USER}" \
                    "${CI_REGISTRY_PASSWORD}"
            ),
            $(
                write_auth \
                    "https://index.docker.io/v1/" \
                    "${DOCKERHUB_REGISTRY_USER}" \
                    "${DOCKERHUB_REGISTRY_PASSWORD}"
            )
        }
}"
