#!/usr/bin/sh

function write_auth {
cat <<EOF
"${1}":
                {
                    "auth": 
                        "$(printf "${2}:${3}")"
                }
EOF
}


printf "%s" \
    "{
        \"auths\":
        {
            $(
                write_auth \
                    "${CI_REGISTRY}" \
                    "${CI_REGISTRY_USER}" \
                    "${CI_REGISTRY_PASSWORD}"
            )
        }
}"
