#!/usr/bin/env bash

source "${DEV_CONTAINER_DIR}/run/dropbear_settings"

mkdir -p "${SSH_KEY_FOLDER}"
mkdir -p "${DROPBEAR_FOLDER}"

action="${1}"

for host_key_type in "${host_key_types[@]}"; do
    if (echo "${action}" | grep -iq "generate"); then
        # Generate host and store host keys
        dropbearkey -t "${host_key_type}" -f "${DROPBEAR_FOLDER}/host_key_${host_key_type}" >/dev/null 2>&1
        openssl base64 <"${DROPBEAR_FOLDER}/host_key_${host_key_type}" >"${SSH_KEY_FOLDER}/host_key_${host_key_type}.txt"
        echo "---"
        cat "${SSH_KEY_FOLDER}/host_key_${host_key_type}.txt"
        echo "---"
        dropbearkey -y -f "${SSH_KEY_FOLDER}/host_key_${host_key_type}.check"
        echo "---"
    elif (echo "${action}" | grep -iq "insert"); then
        # Insert predefined host keys
        cat "${SSH_KEY_FOLDER}/host_key_${host_key_type}.txt" | openssl base64 -d >"${DROPBEAR_FOLDER}/host_key_${host_key_type}"
    else
        printf "$(tput_red "%s")\n" "First (any only) argument to ${BASH_SOURCE[0]} should be 'generate' or 'insert'." >&2
        exit 1
    fi
done
