#!/usr/bin/env bash

key_warned=0
unchanged_keys=()

function key_has_changed {
    current_key="$(cat ./dropbear_${1}_host_key.txt)"

    if [[ "${1}" == "ecdsa" ]]; then
        org_key="AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOxZYSR9SXAD
61T1YdJShe7aZgaOVD09ATyrPGik9erSV6TxsCx06a6TcXJ9yheKTVEd6wMPYada
z23B+4607gQAAAAhAKGbRj6oGnAmsVJZct4MUVQIl45F37CoDYHbPzuYfOfp"
        ((key_warned++))
    elif [[ "${1}" == "ed25519" ]]; then
        org_key="AAAAC3NzaC1lZDI1NTE5AAAAQOthyqGnCYeVFvmgehopuvum7NqbxYgJZTRdf/AF
ndbKGqrkutuXfzpjliUKaSMgN1VQfUpRQ08CxAK+EnP92+c="
        ((key_warned++))
    elif [[ "${1}" == "rsa" ]]; then
        org_key="AAAAB3NzaC1yc2EAAAADAQABAAABAQC0roumY9gtiteU4WX68ktyoUDRFuz20E1T
PvtoxeNsp3xmkIY9poK+TgY9toWNNjqYVScvZIa/UPC6SLLuwhmrf1MUTJRvpatH
2Y2j4d5lKRQ//eSs9kmX4SEfG6uEbT27FVkSTusAvT1ny02+hzceTyMfPIVOaFIM
siNQFH/xsMR/iR1dxlucvfT0Z0Y9JDYaz1oqV2D0zmmoKT28zB2gezqc6B9z2S2X
lV0BD1hVZT33vRKdg188TDXGW2kr2jhRArMXNjXHyBXnjdkNjrCexZZHZXPxv+2F
IRljyXgPCOC5AEgrLGP0loeL9ZxWAUWei4K7DbZ7ziVojNczR1CRAAABAA8we0n+
K87MVMpN1pptox0cZEwPntUy9sUwTsdkl3VrcSBYNwjYxjYEbi7i+MBB1lQ3GGe6
Dj/oKIyoju5Wf/z0Y8IZnAL0zPzp06f61YzwkqS8jexiehZcFUI9u8ISwvVG2qmY
29XAkvh2VW9Wg7I3Ge9G0bghOgCaOzDAwG7Ldm4LHaGHBdPiPaXMVA1SbToEWXv6
quO/DTxCDm7VCQSDzUo85UGJKSBd2++riiDKdEjZS950KoV4CkF+UA+Z8YuPHQO2
sNVl/jN0gCa9OkaU9unYPcLFrEPui5vAPerFPiAnTIjWZOiw3Aey2ZLL7tp7ns0D
MqRJsFLwX8UUR+cAAACBALjcfxihxHIY+2s+J9Oc9TvUg6fsIqkoyzhG2U0CsPJN
FMEE77dn6fnUCJWwZe/LTdlVQA1XNizinEzKr5IHuew5b0VF3rAELfGT3oD+a9nJ
e5PSpgVhx+Ok//TYqBwkgQqPkB8KqZXFfmPd9R25EPda0E9+vEpmwcT0+Fa7ipD3
AAAAgQD6Nk72+VuM3g/U0jKhXNs+vmGmqGsWnPgcnnhbLxVwEZc53WF26y4nroB5
dhcxF1GKcXyvayWWFOR/jVAvbdHbb+YcQZGr6Gkd0v1+Vdaop9XA/tXMyw1vHkkT
5SngqqgifFvYvGG75V1irw2P2EZCZYkwvlnZNNaicwlaItfQtw=="
        ((key_warned++))
    fi

    if [[ "${current_key}" == "${org_key}" ]]; then
        exit 1
    fi

    exit 0
}

key_types=($(ls | grep "dropbear_.*_host_key.txt" | perl -p0e "s/dropbear_(.*)_host_key.txt/\${1}/gmi"))

for key_type in "${key_types[@]}"; do
    :
    (key_has_changed "${key_type}") || {
        unchanged_keys+=("${key_type}")
    }
done

if [ ${#unchanged_keys[@]} -eq 0 ]; then exit 0; fi

(command -v "tput" >/dev/null 2>&1) &&
    {
        # Format for folder
        function tput_red {
            echo "$(tput bold)$(tput setaf 1)$1$(tput sgr0)"
        }
    } || {
        function tput_red {
            echo "$5"
        }
}

printf "$(tput_red %s)\n" "The following keys are unchanged:"

printf "\t$(tput_red "- %s")\n" "${unchanged_keys[@]}"

printf "$(tput_red "%s")\n" "This poses security risks as they are publicly available."

exit 1