#!/usr/bin/env bash

# ┌┌────────────────────────────────────────────────────────────────────────┐┐ #
# ││ Dependencies:                                                          ││ #
# ││ ./scripts/run/print_functions                                          ││ #
# ││ └─ [Optional] tput                                                     ││ #
# └└────────────────────────────────────────────────────────────────────────┘┘ #

# ======================= > Check tput availability < ======================== #

(command -v "tput" >/dev/null 2>&1) && {
    export tput_available=true
} || {
    export tput_available=false
}

if [ -z "${TERM}" ]; then
    export tput_available=false
fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============== > Functions for conditional tput formatting < =============== #

function use_tput {
    if [[ "${tput_available}" == "true" ]]; then
        tput $@
    fi
}

# Set formatting functions
function tput_file {
    col="${2}"
    if [ -z "${col}" ]; then
        col=0
    fi
    echo "$(use_tput setaf ${col} && use_tput bold && use_tput smul)$1$(use_tput sgr0)"
}

function tput_command {
    col="${2}"
    if [ -z "${col}" ]; then
        col=0
    fi
    echo "$(use_tput setaf ${col} && use_tput bold)$1$(use_tput sgr0)"
}

function tput_red {
    echo "$(use_tput setaf 1)$1$(use_tput sgr0)"
}
function tput_green {
    echo "$(use_tput setaf 2)$1$(use_tput sgr0)"
}

function tput_bold {
    echo "$(use_tput bold)$1$(use_tput sgr0)"
}

function tput_underline {
    echo "$(use_tput smul)$1$(use_tput rmul)"
}

function tput_keys {
    echo "$(use_tput setaf 1 && use_tput bold)$1 $2$(use_tput sgr0)"
}

function tput_store_cursor {
    echo "$(use_tput sc)"
}

function tput_restore_and_clear {
    if [[ "${tput_available}" == "true" ]]; then
        tput rc && tput ed && tput rc
    fi
}

function err {
    printf "%b " "$(use_tput setaf 1)${@}$(use_tput sgr0)" >&2
}

# ────────────────────────────────── <end> ─────────────────────────────────── #
