#!/usr/bin/env bash

# Do this only if the current terminal runs in vscode
if [[ ! "${TERM_PROGRAM}" == "vscode" ]]; then exit 0; fi

# ============================== > Arguments < =============================== #
# $1: Target folder
folder="${1:-$HOME}"
# $2: Time limit for this script to be executed
time_limit="${2:-5 minutes}"
# $3: Path to .bashrc file
bashrc_path="${3:-$HOME/.bashrc}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# =============================== > Settings < =============================== #

norm_folder="$(perl -p0e "s/[\/\\\\]/_/gi" <<<"${folder}")"

# The file to store timestamp in
time_filename="$DEV_CONTAINER_DIR/run/tmp/set_vscode_folder_${norm_folder}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ======================== > Check time difference < ========================= #
# If `time_varname` is still empty: define variable beyond `time_limit`
echo "time_filename: $time_filename"
if [ -f ${time_filename} ]; then
    prev_time="$(cat "${time_filename}")"
else
    prev_time="$(date -I"seconds" -d "-${time_limit}")"
fi

timediff="$((("$(date +%s -d "-${time_limit}")" - $(date -d ${prev_time} +%s))))"

# If the folder was changed less than `timediff` ago: end script
if [ ${timediff} -lt 0 ]; then exit 0; fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ======================= >  Move vscode to `folder` < ======================= #
code -r "${folder}"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ====================== > Store timestamp in .bashrc < ====================== #
# If write current timestap to `time_filename`
echo "$(date -I"seconds")" >"${time_filename}"
# ────────────────────────────────── <end> ─────────────────────────────────── #
