#!/usr/bin/env bash

# Do this only if the current terminal runs in vscode
if [[ ! "${TERM_PROGRAM}" == "vscode" ]]; then exit 0; fi

# ============================== > Arguments < =============================== #
# $1: Target folder
folder="${1:-$HOME}"

# Fully expand target folder
folder="$(readlink -f $(eval "echo "${folder}""))"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ================== > Check if already in target folder < =================== #
current_folder="$(readlink -f $(eval "echo "${PWD}""))"
if [[ "${current_folder}" == "${folder}" ]]; then exit 0; fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ======================= > Offer user to move vscode to `folder` < ======================= #

(command -v "tput" >/dev/null 2>&1) &&
    {
        function folder_fmt {
            echo "$(tput bold)$(tput setaf 1)$1$(tput sgr0)"
        }
        function key_fmt {
            echo "$(tput bold)$(tput setaf 5)$1$(tput sgr0)"
        }
    } || {
    function folder_fmt {
        echo "$1"
    }
    function key_fmt {
        echo "$1"
    }
}

(command -v "tput" >/dev/null 2>&1) && tput sc

printf "Moving vscode to\n%s\nin 3 secs.\n" "$(folder_fmt "${folder}")"
printf "\t%-35s%20s\n" \
    "$(key_fmt "ESCAPE")" "$(key_fmt "cancel")" \
    "$(key_fmt "Any other")" "$(key_fmt "proceed")"
read -s -n 1 -t 3 key

(command -v "tput" >/dev/null 2>&1) && tput rc && echo -e "\033[0J" && tput rc

if [[ "$key" == $'\e' ]]; then
    printf "OK, staying in\n\t%s\n" "$(folder_fmt "${current_folder}")"
    exit 0
fi

printf "Moving to\n\t%s\n" "$(folder_fmt "${folder}")"
code -r "${folder}"

exit 0
# ────────────────────────────────── <end> ─────────────────────────────────── #
