#!/usr/bin/env bash

# ┌┌────────────────────────────────────────────────────────────────────────┐┐ #
# ││ Dependencies:                                                          ││ #
# ││ ./scripts/run/ssh_key_check                                            ││ #
# ││ └─ ./scripts/run/dropbear_settings                                     ││ #
# ││ └─ ./scripts/run/print_functions                                       ││ #
# └└────────────────────────────────────────────────────────────────────────┘┘ #

# ========================= > Source dependencies < ========================== #
source "${DEV_CONTAINER_DIR}/run/dropbear_settings"
source "${DEV_CONTAINER_DIR}/run/print_functions"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# List key files
key_files=($(ls "${SSH_KEY_FOLDER}" | grep -v "user_id$"))

# Declare arrays of (un)changed key files
unchanged_key_files=()
changed_key_files=()

# Loop over keys
for key_file in "${key_files[@]}"; do
    key="$(cat "${SSH_KEY_FOLDER}/$key_file")"
    default_key="$(
        cat "${DEV_CONTAINER_DIR}/run/.default_ssh_keys/$key_file" ||
            echo ""
    )"
    # If keys are in list of default keys:
    # add key_file to `unchanged_key_files`,
    # otherwise to `changed_key_files`
    if [[ "${default_key}" == "${key}" ]]; then
        unchanged_key_files+=("${key_file}")
    else
        changed_key_files+=("${key_file}")
    fi
done

# Check if all key files were changed
if [ ${#unchanged_key_files[@]} -eq 0 ]; then exit 0; fi

# Otherwise: warn user
err \
    "Warning:" \ 
"The following key files are unchanged:"
err "" "$(
    printf "  - $(tput_file "%s" 1)\n" \
        "${unchanged_key_files[@]}"
)"
err "" \
    "This poses security risks as they are publicly available."

printf "%b\n" \
    "Please consider changing the keys in $(tput_file "${SSH_KEY_FOLDER}" 2) by" \
    "$(tput_bold [a]) mounting a folder to $(tput_file "${SSH_KEY_FOLDER}" 2)" \
    "    with files corresponding to those in $(tput_file "./scripts/ssh_keys" 2) and/or" \
    "$(tput_bold [b]) running $(tput_file "$DEV_CONTAINER_DIR/run/ssh_key_setup" \"generate\" 2)" \
    "When combining $(tput_bold [a]) and $(tput_bold [b]), the keys will be in the mounted folder and easily re-usable." \
    >&2

exit 1
