#!/usr/bin/env bash

# =============================== > Settings < =============================== #
source "$(readlink -f $(dirname ${BASH_SOURCE[0]}))/dropbear_settings"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# Read list of default keys
if [ -f ${default_key_file} ]; then
    default_keys="$(
        cat "${default_key_file}" |
            grep -v "$(basename "${default_key_file}")"
    )"
fi

# List key files
key_files=($(ls "${SSH_KEY_FOLDER}" | grep -v "user_id$"))

# Declare arrays of (un)changed key files
unchanged_key_files=()
changed_key_files=()

# Loop over keys
for key_file in "${key_files[@]}"; do
    key="$(cat "${SSH_KEY_FOLDER}/$key_file")"
    # If keys are in list of default keys:
    # add key_file to `unchanged_key_files`,
    # otherwise to `changed_key_files`
    if (echo "${default_keys}" | grep -iq "${key}"); then
        unchanged_key_files+=("${key_file}")
    else
        changed_key_files+=("${key_file}")
    fi
done

# If this script is run from a file in `git/hooks`
if (dirname "${BASH_SOURCE[-1]}" | grep -iq "git/hooks"); then
    # Write `changed_key_files` to `default_key_file`,
    # since these files are likely published on git
    for key_file in "${changed_key_files[@]}"; do
        printf "%s\n\n" "$(cat "${SSH_KEY_FOLDER}/${key_file}")" >>"${default_key_file}"
    done
    git add "${default_key_file}"
else
    # Check if all key files were changed
    if [ ${#unchanged_key_files[@]} -eq 0 ]; then exit 0; fi

    printf "$(tput_red %s)\n" "The following key files are unchanged:" >&2
    printf "\t$(tput_red "$(tput_bold "- %s")")\n" "${unchanged_key_files[@]}" >&2
    printf "$(tput_red "%s")\n" "This poses security risks as they are publicly available." >&2
    printf "$(tput_green "%s\n%-15s%s\n%-15s%s")\n" \
        "Please consider changing the keys in" \
        "./ssh_keys" \
        "$(tput_underline "(outside container)")" \
        "/etc/dropbear" \
        "$(tput_underline "(inside container)")" \
        >&2
fi
