#!/usr/bin/env bash

if [ -n "${__entrypoint_run__}" ]; then return; fi
export __entrypoint_run__=true

function __containr_entrypoint_log__ {
    printf "%-25s %-50s" \
        "${1}" "${2} ..."
} 

# =========================== > Environment File < =========================== #
# ┌┌────────────────────────────────────────────────────────────────────────┐┐ #
# ││ This will check for an environment file and source it if it is there   ││ #
# └└────────────────────────────────────────────────────────────────────────┘┘ #

CONTAINER_ENV_FILE=/.env

if [ -f ${CONTAINER_ENV_FILE} ]; then
    __containr_entrypoint_log__ "sourcing" "$CONTAINER_ENV_FILE"
    source ${CONTAINER_ENV_FILE} && printf "%s\n" "ok" || printf "%s\n" "failed"
fi

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============================ > Create folders < ============================ #
__containr_entrypoint_log__ "creating" "$WORKDIR"
mkdir -p ${WORKDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"

__containr_entrypoint_log__ "creating" "$OUTDIR"
mkdir -p ${OUTDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ============= > Copy global .Rprofile and add path messages < ============== #

function copy_rprofile {
    # If .Rprofile does not exist in folder
    if [ ! -f ${1}/.Rprofile ]; then
        # # Copy /.Rprofile to folder
        # cp /.Rprofile ${1}/
        # # Change log message in .Rprofile to contain folder
        # sed -i 's|\(Loading\s*\).*\/\(.Rprofile\)|\1'"${1}"'\2|' ${1}/.Rprofile

        # Create symbolic link in folder
        ln -s /.Rprofile ${1}/.Rprofile 2>/dev/null || echo ""
    fi
}
__containr_entrypoint_log__ "copying .Rprofile to" "$HOME"
copy_rprofile ${HOME}/ && printf "%s\n" "ok" || printf "%s\n" "failed"
__containr_entrypoint_log__ "copying .Rprofile to" "$WORKDIR"
copy_rprofile ${WORKDIR} && printf "%s\n" "ok" || printf "%s\n" "failed"

# ────────────────────────────────── <end> ─────────────────────────────────── #

# ================ > Link folders to user's home directory < ================= #
if [[ ! -d ${HOME}/$(basename $WORKDIR)/ ]]; then
    ln -s $WORKDIR/ ${HOME}/$(basename $WORKDIR)/
fi
if [[ ! -d ${HOME}/$(basename $OUTDIR)/ ]]; then
    ln -s $OUTDIR/ ${HOME}/$(basename $OUTDIR)/
fi
# ────────────────────────────────── <end> ─────────────────────────────────── #

# ===================== > Enter projects input folder < ====================== #
__containr_entrypoint_log__ "entering" "${HOME}/$(basename $WORKDIR)"
cd ${HOME}/$(basename $WORKDIR) && printf "%s\n" "ok" || printf "%s\n" "failed"
# ────────────────────────────────── <end> ─────────────────────────────────── #

exec "$@"
