.base-template:
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folder 
    - cd "${CI_PROJECT_DIR}";
    - >-
      # Determine image information
      export IMAGE_NAME="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
      export IMAGE_VERS="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')"; 
      # Set credentials
    - export FULL_AUTH_FILE="$(readlink -f ${AUTH_FILE})";
    - printf "%s\n" "FULL_AUTH_FILE: $FULL_AUTH_FILE";
    - mkdir -p "$(dirname "${FULL_AUTH_FILE}")";
    - source ".gitlab-ci/set_credentials" > "${FULL_AUTH_FILE}";

