.base-template:
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folder 
    - cd "${CI_PROJECT_DIR}";
      # Determine image information
    - export IMAGE_NAME="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
    - export IMAGE_VERS="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')"; 
    # Set credentials
    - export AUTH_FILE="$(readlink -f ${AUTH_FILE})";
    - echo "AUTH_FILE: $AUTH_FILE";
    - mkdir -p "$(dirname "${AUTH_FILE}")";
    - source ".gitlab-ci/set_credentials" > "${AUTH_FILE}";
