.base-template:
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folder 
    - cd "${CI_PROJECT_DIR}";
      # Determine image information
    - export IMAGE_NAME="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
    - export IMAGE_VERS="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')"; 
    - export AUTH_FILE="$( printf -- "$AUTH_FILE" | sed "s|~\/|$HOME\/|g" )";
    - if [ -z "${AUTH_FILE}" ]; then echo "Missing \$AUTH_FILE!" >&2; exit 1; fi
      # Set credentials
    - mkdir -p "$(dirname "${AUTH_FILE}")";
    - source ".gitlab-ci/set_credentials" > "${AUTH_FILE}";

