.base-template:
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folders
    - cd "${CI_PROJECT_DIR}";
    # Determine image information
    - >-
      export IMAGE_NAME="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
      export IMAGE_VERS="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')"; 
    # Set Credentials
    - mkdir -p $HOME/.docker/;
    - source ".gitlab-ci/set_credentials" >$HOME/.docker/config.json;