.build-container:
  stage: container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - Dockerfile
          - .gitlab-ci.yml
  script:
    # Set folders
    - cd "${CI_PROJECT_DIR}" && mkdir -p /kaniko/.docker;
    # Set Credentials
    - source ".gitlab-ci/set_credentials";
    # Determine image information
    - >-
      export image_name="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
      export image_vers="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')";
    # Export Image Paths
    - >-
      export GITLAB_REGISTRY_PATH="${CI_REGISTRY_IMAGE}/${image_name}";
      export DOCKERHUB_REGISTRY_PATH="index.docker.io/simonlenau/dev-container:${image_name}";  
    # Build container
    - source .gitlab-ci/build-container
