.build-container:
  stage: container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folders
    - cd "${CI_PROJECT_DIR}" && mkdir -p /kaniko/.docker;
    # Set Credentials
    - source ".gitlab-ci/set_credentials";
    # Export package lists
    - >- 
      export ubuntu_packages=$(cat dependencies/Ubuntu 2>/dev/null || return 0);
      # export r_packages=$(cat dependencies/R 2>/dev/null || return 0);
      # export python_packages=$(cat dependencies/python 2>/dev/null || return 0);
    # Determine image information
    - >-
      export IMAGE_NAME="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
      export IMAGE_VERS="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')"; 
    # Build container
    # - source .gitlab-ci/build-container
    - >-
      export GITLAB_REGISTRY_MAIN_PATH="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}";
      export DOCKERHUB_REGISTRY_PATH="index.docker.io/simonlenau/dev-container:${IMAGE_NAME}"; 
      export GITLAB_REGISTRY_PATH="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${IMAGE_NAME}";
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/"
      --dockerfile "Dockerfile"
      --build-arg "ubuntu_packages"="${ubuntu_packages}"
      --build-arg "r_packages"="${r_packages}"
      --build-arg "python_packages"="${python_packages}"
      --build-arg "workdir"="/${CI_PROJECT_TITLE}/"
      --build-arg "outdir"="/${CI_PROJECT_TITLE}_output/"
      --build-arg "FROM_IMAGE"="${FROM_IMAGE}"
      --destination "${GITLAB_REGISTRY_PATH}:${IMAGE_VERS}"
      --destination "${GITLAB_REGISTRY_PATH}:latest"
      --destination "${GITLAB_REGISTRY_MAIN_PATH}:${IMAGE_VERS}"
      --destination "${GITLAB_REGISTRY_MAIN_PATH}:latest"
      --destination "${DOCKERHUB_REGISTRY_PATH}_${IMAGE_VERS}"
      --destination "${DOCKERHUB_REGISTRY_PATH}_latest";
