.build-container:
  stage: container-build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        paths:
          - dependencies/*
          - scripts/**/*
          - ssh_keys/*
          - .gitlab-ci/**/*
          - .gitlab-ci.yml
          - Dockerfile
  script:
    # Set folders
    - cd "${CI_PROJECT_DIR}" && mkdir -p /kaniko/.docker;
    # Set Credentials
    - source ".gitlab-ci/set_credentials";
    # Export package lists
    - >- 
      export ubuntu_packages=$(cat dependencies/Ubuntu 2>/dev/null || return 0);
      export r_packages=$(cat dependencies/R 2>/dev/null || return 0);
      export python_packages=$(cat dependencies/python 2>/dev/null || return 0);
    # Determine image information
    - >-
      export image_name="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/\:.*$//')";
      export image_vers="$(echo ${FROM_IMAGE} | sed 's/.*\///' | sed 's/^.*\:\(.*\)$/\1/')";
    # Export Image Paths
    - >-
      export GITLAB_REGISTRY_PATH="${CI_REGISTRY_IMAGE}/${image_name}";
      export DOCKERHUB_REGISTRY_PATH="index.docker.io/simonlenau/dev-container:${image_name}";  
    # Build container
    - printf "- %s\n" "$(ls -a)"
    - ${CI_PROJECT_DIR}/.gitlab-ci/build-container
