

.copy-container:
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - cat /kaniko/.docker/config.json;
    - printf "%s\n"  "$(ls)";
    - printf -- "A: ${A}";
