include:
  - local: '.gitlab-ci/templates/master.yaml'

.forward-container:
  extends: .master
  stage: container-forward
  script:
    - echo "FROM "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}/${IMAGE_NAME}:${IMAGE_VERS}"" >> Dockerfile
    - export GITLAB_REGISTRY_MAIN_PATH="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}";
    - export DOCKERHUB_REGISTRY_PATH="index.docker.io/simonlenau/dev-container:${IMAGE_NAME}"; 
    # Build container
    - >-
      /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --destination "${GITLAB_REGISTRY_MAIN_PATH}:latest"
      --destination "${GITLAB_REGISTRY_MAIN_PATH}:${IMAGE_VERS}";
